[package]
name = "db-migration-tool"
version = "0.1.0"
authors = ["aoyagikouhei <aoyagi_kouhei@uniquevision.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33"